### PR TITLE
Wilke/check stderr for success

### PR DESCRIPTION
**Pull request by wilke**

### CODE REVIEW

**Comment by ikalash** [comment]
Thanks for making these changes.  However, I'm still finding that the bulk of the test output gets sent to error.log, including the successful output: 

```
test_access_attributes_filled (test.config_test.TestSession) ... ok
test_create_session (test.config_test.TestSession) ... ok
test_is_class (test.config_test.TestSession) ... ok

----------------------------------------------------------------------
Ran 4 tests in 0.001s

OK
```
Is that not the case when you run?

**Comment by wilke** [comment]
I think we should setup tests for master and develop (I just created develop). I merged my changes into develop, is it failing there too?


On Apr 10, 2019, at 12:44 PM, Irina K. Tezaur <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for making these changes. However, I'm still finding that the bulk of the test output gets sent to error.log, including the successful output:

test_access_attributes_filled (test.config_test.TestSession) ... ok
test_create_session (test.config_test.TestSession) ... ok
test_is_class (test.config_test.TestSession) ... ok

----------------------------------------------------------------------
Ran 4 tests in 0.001s

OK


Is that not the case when you run?

**Comment by wilke** [comment]
Actually I think the last step in the test will fail.

On Apr 10, 2019, at 3:07 PM, Wilke, Andreas <wilke@mcs.anl.gov<mailto:wilke@mcs.anl.gov>> wrote:

I think we should setup tests for master and develop (I just created develop). I merged my changes into develop, is it failing there too?


On Apr 10, 2019, at 12:44 PM, Irina K. Tezaur <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for making these changes. However, I'm still finding that the bulk of the test output gets sent to error.log, including the successful output:

test_access_attributes_filled (test.config_test.TestSession) ... ok
test_create_session (test.config_test.TestSession) ... ok
test_is_class (test.config_test.TestSession) ... ok

----------------------------------------------------------------------
Ran 4 tests in 0.001s

OK


Is that not the case when you run?

**Comment by ikalash** [comment]
You're right I was using master, but I just checked and the problem occurs in develop as well.

**Pull request merged**
